# Generated by Django 2.0.2 on 2018-08-21 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonafide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bitsId', models.CharField(max_length=15)),
                ('gender', models.CharField(blank=True, max_length=1)),
                ('cgpa', models.FloatField(blank=True, null=True)),
                ('admit', models.DateField(blank=True, null=True)),
                ('ps', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='bonafide',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
    ]
