# Generated by Django 2.0.2 on 2018-08-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bonafide',
            new_name='Graduating',
        ),
        migrations.RemoveField(
            model_name='student',
            name='admit',
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
