# Generated by Django 2.0.2 on 2018-08-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180821_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bitsId',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
