# Generated by Django 2.0.2 on 2018-08-21 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180821_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='ps',
        ),
    ]
